### ISSUE TITLE
VillagerInventoryの例外処理

### ISSUE THREAD

**Issue by ttk1** [ttk1/Katsuage#1]
インベントリのスロット数が9の倍数でないとopenInventoryをした際に正しく表示されない。
VillagerInventoryクラスはそれを回避するために作成したが、村人のインベントリのスロットは8個しかないので、一番右のスロットにアイテムを置くと例外が発生する。

例外が発生しないように修正する。

**Comment by nankachiisai** [comment]
修正しました。
